/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ir.ac.iut.sccportal.guestdiscussion.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortletTitle service. Represents a row in the &quot;GDP_PortletTitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ir.ac.iut.sccportal.guestdiscussion.model.impl.PortletTitleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ir.ac.iut.sccportal.guestdiscussion.model.impl.PortletTitleImpl}.
 * </p>
 *
 * @author Alireza
 * @see PortletTitle
 * @see ir.ac.iut.sccportal.guestdiscussion.model.impl.PortletTitleImpl
 * @see ir.ac.iut.sccportal.guestdiscussion.model.impl.PortletTitleModelImpl
 * @generated
 */
public interface PortletTitleModel extends BaseModel<PortletTitle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portlet title model instance should use the {@link PortletTitle} interface instead.
	 */

	/**
	 * Returns the primary key of this portlet title.
	 *
	 * @return the primary key of this portlet title
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this portlet title.
	 *
	 * @param primaryKey the primary key of this portlet title
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the portlet ID of this portlet title.
	 *
	 * @return the portlet ID of this portlet title
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this portlet title.
	 *
	 * @param portletId the portlet ID of this portlet title
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the title ID of this portlet title.
	 *
	 * @return the title ID of this portlet title
	 */
	public long getTitleId();

	/**
	 * Sets the title ID of this portlet title.
	 *
	 * @param titleId the title ID of this portlet title
	 */
	public void setTitleId(long titleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ir.ac.iut.sccportal.guestdiscussion.model.PortletTitle portletTitle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ir.ac.iut.sccportal.guestdiscussion.model.PortletTitle> toCacheModel();

	@Override
	public ir.ac.iut.sccportal.guestdiscussion.model.PortletTitle toEscapedModel();

	@Override
	public ir.ac.iut.sccportal.guestdiscussion.model.PortletTitle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}