/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ir.ac.iut.sccportal.guestdiscussion.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Title service. Represents a row in the &quot;GDP_Title&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ir.ac.iut.sccportal.guestdiscussion.model.impl.TitleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ir.ac.iut.sccportal.guestdiscussion.model.impl.TitleImpl}.
 * </p>
 *
 * @author Alireza
 * @see Title
 * @see ir.ac.iut.sccportal.guestdiscussion.model.impl.TitleImpl
 * @see ir.ac.iut.sccportal.guestdiscussion.model.impl.TitleModelImpl
 * @generated
 */
public interface TitleModel extends BaseModel<Title> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a title model instance should use the {@link Title} interface instead.
	 */

	/**
	 * Returns the primary key of this title.
	 *
	 * @return the primary key of this title
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this title.
	 *
	 * @param primaryKey the primary key of this title
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the title ID of this title.
	 *
	 * @return the title ID of this title
	 */
	public long getTitleId();

	/**
	 * Sets the title ID of this title.
	 *
	 * @param titleId the title ID of this title
	 */
	public void setTitleId(long titleId);

	/**
	 * Returns the group ID of this title.
	 *
	 * @return the group ID of this title
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this title.
	 *
	 * @param groupId the group ID of this title
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this title.
	 *
	 * @return the company ID of this title
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this title.
	 *
	 * @param companyId the company ID of this title
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this title.
	 *
	 * @return the user ID of this title
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this title.
	 *
	 * @param userId the user ID of this title
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this title.
	 *
	 * @return the user uuid of this title
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this title.
	 *
	 * @param userUuid the user uuid of this title
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this title.
	 *
	 * @return the user name of this title
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this title.
	 *
	 * @param userName the user name of this title
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this title.
	 *
	 * @return the create date of this title
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this title.
	 *
	 * @param createDate the create date of this title
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the title text of this title.
	 *
	 * @return the title text of this title
	 */
	@AutoEscape
	public String getTitleText();

	/**
	 * Sets the title text of this title.
	 *
	 * @param titleText the title text of this title
	 */
	public void setTitleText(String titleText);

	/**
	 * Returns the new comment draft of this title.
	 *
	 * @return the new comment draft of this title
	 */
	@AutoEscape
	public String getNewCommentDraft();

	/**
	 * Sets the new comment draft of this title.
	 *
	 * @param newCommentDraft the new comment draft of this title
	 */
	public void setNewCommentDraft(String newCommentDraft);

	/**
	 * Returns the answer comment draft of this title.
	 *
	 * @return the answer comment draft of this title
	 */
	@AutoEscape
	public String getAnswerCommentDraft();

	/**
	 * Sets the answer comment draft of this title.
	 *
	 * @param answerCommentDraft the answer comment draft of this title
	 */
	public void setAnswerCommentDraft(String answerCommentDraft);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ir.ac.iut.sccportal.guestdiscussion.model.Title title);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ir.ac.iut.sccportal.guestdiscussion.model.Title> toCacheModel();

	@Override
	public ir.ac.iut.sccportal.guestdiscussion.model.Title toEscapedModel();

	@Override
	public ir.ac.iut.sccportal.guestdiscussion.model.Title toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}