/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ir.ac.iut.sccportal.guestdiscussion.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ir.ac.iut.sccportal.guestdiscussion.model.Title;
import ir.ac.iut.sccportal.guestdiscussion.service.TitleLocalServiceUtil;

/**
 * The extended model base implementation for the Title service. Represents a row in the &quot;GDP_Title&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TitleImpl}.
 * </p>
 *
 * @author Alireza
 * @see TitleImpl
 * @see ir.ac.iut.sccportal.guestdiscussion.model.Title
 * @generated
 */
public abstract class TitleBaseImpl extends TitleModelImpl implements Title {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a title model instance should use the {@link Title} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TitleLocalServiceUtil.addTitle(this);
		}
		else {
			TitleLocalServiceUtil.updateTitle(this);
		}
	}
}